language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
- export TZ=Europe/Zurich

script:
  - npm run build
  - npm run test:unit -- --coverage

after_success: coveralls < coverage/lcov.info
